# Generated by Django 6.0.1 on 2026-08-15 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_locality_price'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='price',
            table='price',
        ),
    ]
