# Generated by Django 6.0.1 on 2026-08-16 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_show'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='location_id',
            new_name='location',
        ),
    ]
