# Generated by Django 5.2.8 on 2026-08-19 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0011_rename_location_id_show_location'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        'ALTER TABLE "shows" '
                        'ALTER COLUMN "created_in" TYPE smallint '
                        'USING EXTRACT(YEAR FROM "created_in")::smallint'
                    ),
                    reverse_sql=(
                        'ALTER TABLE "shows" '
                        'ALTER COLUMN "created_in" TYPE timestamp with time zone '
                        "USING make_timestamptz(\"created_in\", 1, 1, 0, 0, 0, 'UTC')"
                    ),
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='show',
                    name='created_in',
                    field=models.PositiveSmallIntegerField(),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('slug', 'website'), name='unique_slug_website'),
        ),
    ]
