# Generated by Django 5.2.8 on 2026-08-19 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0015_artist_types_artist_unique_firstname_lastname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='types',
        ),
        migrations.CreateModel(
            name='ArtistType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='a_artistTypes', to='catalogue.artist')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='t_artistTypes', to='catalogue.type')),
            ],
            options={
                'db_table': 'artist_type',
            },
        ),
        migrations.CreateModel(
            name='ArtistTypeShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artistTypeShows', to='catalogue.artisttype')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artistTypeShows', to='catalogue.show')),
            ],
            options={
                'db_table': 'artist_type_show',
            },
        ),
        migrations.AddField(
            model_name='show',
            name='artist_types',
            field=models.ManyToManyField(related_name='shows', through='catalogue.ArtistTypeShow', to='catalogue.artisttype'),
        ),
        migrations.AddConstraint(
            model_name='artisttype',
            constraint=models.UniqueConstraint(fields=('artist', 'type'), name='unique_artist_type'),
        ),
        migrations.AddConstraint(
            model_name='artisttypeshow',
            constraint=models.UniqueConstraint(fields=('show', 'artist_type'), name='unique_show_artist_type'),
        ),
    ]
