# Generated by Django 5.2.8 on 2026-08-19 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0016_remove_artist_types_artisttype_artisttypeshow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='prices',
            field=models.ManyToManyField(db_table='price_show', related_name='shows', to='catalogue.price'),
        ),
        migrations.AddConstraint(
            model_name='price',
            constraint=models.UniqueConstraint(fields=('type', 'start_date', 'end_date'), name='unique_price_period'),
        ),
    ]
