# Generated by Django 5.2.8 on 2026-08-20 10:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0017_show_prices_price_unique_price_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepresentationReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('representation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representation_reservations', to='catalogue.representation')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representation_reservations', to='catalogue.reservation')),
            ],
            options={
                'db_table': 'representation_reservation',
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='representations',
            field=models.ManyToManyField(related_name='reservations', through='catalogue.RepresentationReservation', to='catalogue.representation'),
        ),
        migrations.AddConstraint(
            model_name='representationreservation',
            constraint=models.UniqueConstraint(fields=('reservation', 'representation'), name='unique_reservation_representation'),
        ),
    ]
